/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Mario Loazno Marquez
 */
public class Alitas extends javax.swing.JFrame {

    
    static String[] datosAlitas;
    static String consultaAlitas = "SELECT * FROM alitas WHERE alitas_nombre = ? AND alitas_tamaño = ?";
    
    static String tipo_Salsa;
    static String tipo_Tamaño;
           
    
    private boolean label3Clicked = false;
    private boolean label7Clicked = false;
    private boolean bbqTxtClick = false;
    private boolean bbpTxtClick = false;
    private boolean picTxtClick = false;
    private boolean manTxtClick = false;
    private boolean tamTxtClick = false;
    public Alitas() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        
        Pedido.MostrarPedido(tbAlitas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelEspacio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpanelTBAlitas = new JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAlitas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lbMenu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bbqBtn = new javax.swing.JPanel();
        bbqTxt = new javax.swing.JLabel();
        picBtn = new javax.swing.JPanel();
        picTxt = new javax.swing.JLabel();
        bbpBtn = new javax.swing.JPanel();
        bbpTxt = new javax.swing.JLabel();
        manBtn = new javax.swing.JPanel();
        manTxt = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tamBtn = new javax.swing.JPanel();
        tamTxt = new javax.swing.JLabel();
        lbConfirmar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelEspacio.setBackground(new java.awt.Color(204, 204, 204));
        jPanelEspacio.setPreferredSize(new java.awt.Dimension(325, 680));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Pedido");

        tbAlitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbAlitas);

        javax.swing.GroupLayout jpanelTBAlitasLayout = new javax.swing.GroupLayout(jpanelTBAlitas);
        jpanelTBAlitas.setLayout(jpanelTBAlitasLayout);
        jpanelTBAlitasLayout.setHorizontalGroup(
            jpanelTBAlitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );
        jpanelTBAlitasLayout.setVerticalGroup(
            jpanelTBAlitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelTBAlitasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelEspacioLayout = new javax.swing.GroupLayout(jPanelEspacio);
        jPanelEspacio.setLayout(jPanelEspacioLayout);
        jPanelEspacioLayout.setHorizontalGroup(
            jPanelEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEspacioLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(156, 156, 156))
            .addGroup(jPanelEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEspacioLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jpanelTBAlitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
        jPanelEspacioLayout.setVerticalGroup(
            jPanelEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEspacioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(643, Short.MAX_VALUE))
            .addGroup(jPanelEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEspacioLayout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addComponent(jpanelTBAlitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(186, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        lbMenu.setBackground(new java.awt.Color(255, 255, 255));
        lbMenu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/regresar.png"))); // NOI18N
        lbMenu.setText("CREAR PEDIDO");
        lbMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Kokos Control1.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SENCILLO");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DOCENA");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        bbqBtn.setBackground(new java.awt.Color(255, 255, 255));
        bbqBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bbqBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bbqTxt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        bbqTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bbqTxt.setText("BBQ");
        bbqTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbqTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbqTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbqTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bbqBtnLayout = new javax.swing.GroupLayout(bbqBtn);
        bbqBtn.setLayout(bbqBtnLayout);
        bbqBtnLayout.setHorizontalGroup(
            bbqBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bbqTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bbqBtnLayout.setVerticalGroup(
            bbqBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bbqTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        picBtn.setBackground(new java.awt.Color(255, 255, 255));
        picBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        picBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        picTxt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        picTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        picTxt.setText("PICOSA");
        picTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                picTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                picTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout picBtnLayout = new javax.swing.GroupLayout(picBtn);
        picBtn.setLayout(picBtnLayout);
        picBtnLayout.setHorizontalGroup(
            picBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(picTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        picBtnLayout.setVerticalGroup(
            picBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(picTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        bbpBtn.setBackground(new java.awt.Color(255, 255, 255));
        bbpBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bbpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bbpTxt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        bbpTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bbpTxt.setText("BBQ PICOSA");
        bbpTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbpTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbpTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbpTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bbpBtnLayout = new javax.swing.GroupLayout(bbpBtn);
        bbpBtn.setLayout(bbpBtnLayout);
        bbpBtnLayout.setHorizontalGroup(
            bbpBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bbpTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bbpBtnLayout.setVerticalGroup(
            bbpBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bbpTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        manBtn.setBackground(new java.awt.Color(255, 255, 255));
        manBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        manBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        manTxt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        manTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manTxt.setText("MANGO HAB");
        manTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout manBtnLayout = new javax.swing.GroupLayout(manBtn);
        manBtn.setLayout(manBtnLayout);
        manBtnLayout.setHorizontalGroup(
            manBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        manBtnLayout.setVerticalGroup(
            manBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Salsas");

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel21.setText("Tamaño ");

        tamBtn.setBackground(new java.awt.Color(255, 255, 255));
        tamBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tamBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tamTxt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tamTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tamTxt.setText("TAMARINDO HAB");
        tamTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tamTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tamTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tamTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout tamBtnLayout = new javax.swing.GroupLayout(tamBtn);
        tamBtn.setLayout(tamBtnLayout);
        tamBtnLayout.setHorizontalGroup(
            tamBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tamBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tamTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tamBtnLayout.setVerticalGroup(
            tamBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tamTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        lbConfirmar.setBackground(new java.awt.Color(255, 153, 0));
        lbConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbConfirmarMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CONFIRMAR");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout lbConfirmarLayout = new javax.swing.GroupLayout(lbConfirmar);
        lbConfirmar.setLayout(lbConfirmarLayout);
        lbConfirmarLayout.setHorizontalGroup(
            lbConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbConfirmarLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        lbConfirmarLayout.setVerticalGroup(
            lbConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbConfirmarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(110, 110, 110)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(picBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bbpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bbqBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(manBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tamBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addComponent(jPanelEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEspacio, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bbpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(picBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(manBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tamBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(lbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuMouseClicked
        CrearPedido cp = new CrearPedido();
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbMenuMouseClicked

    private void lbMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuMouseEntered
        jPanel3.setBackground(Color.orange);
    }//GEN-LAST:event_lbMenuMouseEntered

    private void lbMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuMouseExited
        jPanel3.setBackground(new Color(247,148,29));
    }//GEN-LAST:event_lbMenuMouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        if(!label3Clicked){
        jPanel5.setBackground(new Color(247,148,29));
        }
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        if(!label3Clicked){
        jPanel5.setBackground(Color.white);
        }
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        if(!label7Clicked){
        jPanel6.setBackground(new Color(247,148,29));
        }
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        if(!label7Clicked){
            jPanel6.setBackground(Color.white);
        }
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        tipo_Tamaño = "sencillo";
        
        label3Clicked = true;
        jPanel5.setBackground(new Color(247,148,29));
        jPanel6.setBackground(Color.white);
    
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        
        tipo_Tamaño = "docena";
        
        label7Clicked = true;
        jPanel6.setBackground(new Color(247,148,29));
        jPanel5.setBackground(Color.white);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void bbqTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbqTxtMouseClicked
        
        tipo_Salsa = "alitas bbq";
        
        bbqTxtClick = true;
        bbqBtn.setBackground(new Color(247,148,29));
        bbpBtn.setBackground(Color.white);
        picBtn.setBackground(Color.white);
        manBtn.setBackground(Color.white);
        tamBtn.setBackground(Color.white);
        
    }//GEN-LAST:event_bbqTxtMouseClicked

    private void bbqTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbqTxtMouseEntered
        // TODO add your handling code here:
        if(!bbqTxtClick){
            bbqBtn.setBackground(new Color(247,148,29));
        }
    }//GEN-LAST:event_bbqTxtMouseEntered

    private void bbqTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbqTxtMouseExited
        // TODO add your handling code here:
        if(!bbqTxtClick){
            bbqBtn.setBackground(Color.white);
        }
    }//GEN-LAST:event_bbqTxtMouseExited

    private void bbpTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbpTxtMouseClicked
        
        tipo_Salsa = "alitas bbq picosa";
        
        bbpTxtClick = true;
        bbpBtn.setBackground(new Color(247,148,29));
        bbqBtn.setBackground(Color.white);
        picBtn.setBackground(Color.white);
        manBtn.setBackground(Color.white);
        tamBtn.setBackground(Color.white);
    }//GEN-LAST:event_bbpTxtMouseClicked

    private void bbpTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbpTxtMouseEntered
        // TODO add your handling code here:
        if(!bbpTxtClick){
            bbpBtn.setBackground(new Color(247,148,29));
        }
    }//GEN-LAST:event_bbpTxtMouseEntered

    private void bbpTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbpTxtMouseExited
        // TODO add your handling code here:
        if(!bbpTxtClick){
            bbpBtn.setBackground(Color.white);
        }
    }//GEN-LAST:event_bbpTxtMouseExited

    private void picTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picTxtMouseClicked
        
        tipo_Salsa = "alitas picosa";
        
        picTxtClick = true;
        picBtn.setBackground(new Color(247, 148, 29));
        bbpBtn.setBackground(Color.white);
        bbqBtn.setBackground(Color.white);
        manBtn.setBackground(Color.white);
        tamBtn.setBackground(Color.white);
    }//GEN-LAST:event_picTxtMouseClicked

    private void picTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picTxtMouseEntered
        // TODO add your handling code here:
        if(!picTxtClick) {
            picBtn.setBackground(new Color(247,148,29));
        }
    }//GEN-LAST:event_picTxtMouseEntered

    private void picTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picTxtMouseExited
        // TODO add your handling code here:
        if(!picTxtClick){
            picBtn.setBackground(Color.white);
        }
    }//GEN-LAST:event_picTxtMouseExited

    private void manTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manTxtMouseClicked
        
        tipo_Salsa = "alitas mango habanero";
        
        manTxtClick = true;
        manBtn.setBackground(new Color(247,148,29));
        bbpBtn.setBackground(Color.white);
        picBtn.setBackground(Color.white);
        bbqBtn.setBackground(Color.white);
        tamBtn.setBackground(Color.white);
    }//GEN-LAST:event_manTxtMouseClicked

    private void manTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manTxtMouseEntered
        // TODO add your handling code here:
        if(!manTxtClick){
            manBtn.setBackground(new Color(247,148,29));
        }
    }//GEN-LAST:event_manTxtMouseEntered

    private void manTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manTxtMouseExited
        // TODO add your handling code here:
        if(!manTxtClick){
            manBtn.setBackground(Color.white);
        }
    }//GEN-LAST:event_manTxtMouseExited

    private void tamTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamTxtMouseClicked
        
        tipo_Salsa = "alitas tamarindo habanero";
        
        tamTxtClick = true;
        tamBtn.setBackground(new Color(247,148,29));
        bbpBtn.setBackground(Color.white);
        picBtn.setBackground(Color.white);
        manBtn.setBackground(Color.white);
        bbqBtn.setBackground(Color.white);
    }//GEN-LAST:event_tamTxtMouseClicked

    private void tamTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamTxtMouseEntered
        // TODO add your handling code here:
        if(!tamTxtClick){
            tamBtn.setBackground(new Color(247,148,29));
        }
    }//GEN-LAST:event_tamTxtMouseEntered

    private void tamTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamTxtMouseExited
        // TODO add your handling code here:
        if(!tamTxtClick){
            tamBtn.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_tamTxtMouseExited

    private void lbConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbConfirmarMouseEntered
        // TODO add your handling code here:
        lbConfirmar.setBackground(Color.orange);
    }//GEN-LAST:event_lbConfirmarMouseEntered

    private void lbConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbConfirmarMouseExited
        // TODO add your handling code here:
        lbConfirmar.setBackground(new Color(247,148,29));
    }//GEN-LAST:event_lbConfirmarMouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        
        Pedido.ConsultarPedidoA();
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        lbConfirmar.setBackground(Color.orange);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        lbConfirmar.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_jLabel4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bbpBtn;
    private javax.swing.JLabel bbpTxt;
    private javax.swing.JPanel bbqBtn;
    private javax.swing.JLabel bbqTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public static javax.swing.JPanel jPanelEspacio;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JPanel jpanelTBAlitas;
    private javax.swing.JPanel lbConfirmar;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JPanel manBtn;
    private javax.swing.JLabel manTxt;
    private javax.swing.JPanel picBtn;
    private javax.swing.JLabel picTxt;
    private javax.swing.JPanel tamBtn;
    private javax.swing.JLabel tamTxt;
    public static javax.swing.JTable tbAlitas;
    // End of variables declaration//GEN-END:variables
}
