
package com.login;

import com.login.menu;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import sql.ConexionSQL;

/**
 *
 * @author hnm77
 */
public class login extends javax.swing.JFrame {
    
    static String [] DatosUser1;
    static String [] DatosUser2;
    static int empleadoA = 1;
    static int empleadoP = 2;
    static String Admin;
    static String admincheck;
    static String usuario;
    
    static String key = "SELECT * FROM usuarios WHERE usuario_id = ?";  
     
    int xMouse, yMouse;
    public login() {
        initComponents();
        ConexionSQL conn = new ConexionSQL();
        DatosUser1 = ConexionSQL.Consol(key, empleadoA);
        DatosUser2 = ConexionSQL.Consol(key, empleadoP);
        passTx.addKeyListener(new java.awt.event.KeyAdapter() 
        {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) 
                {
                    txEntrarMouseClicked(null); // Llama al método de clicar el botón "Entrar"
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userTx = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        passTx = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        txEntrar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        extBtn = new javax.swing.JPanel();
        txBtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txLogin.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        txLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txLogin.setText("INICIAR SESIÓN");
        txLogin.setToolTipText("");
        jPanel1.add(txLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        userTx.setForeground(new java.awt.Color(204, 204, 204));
        userTx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userTx.setText("Ingrese su usuario");
        userTx.setToolTipText("");
        userTx.setBorder(null);
        userTx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxMousePressed(evt);
            }
        });
        userTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxActionPerformed(evt);
            }
        });
        userTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userTxKeyTyped(evt);
            }
        });
        jPanel1.add(userTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 242, 29));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 242, 10));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 242, 10));

        passTx.setForeground(new java.awt.Color(204, 204, 204));
        passTx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passTx.setText("********");
        passTx.setBorder(null);
        passTx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTxMousePressed(evt);
            }
        });
        passTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTxActionPerformed(evt);
            }
        });
        jPanel1.add(passTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 242, 30));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        txEntrar.setBackground(new java.awt.Color(255, 153, 0));
        txEntrar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txEntrar.setForeground(new java.awt.Color(255, 255, 255));
        txEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txEntrar.setText("ENTRAR");
        txEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 90, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logoY.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, -1, 290, 470));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        extBtn.setBackground(new java.awt.Color(255, 255, 255));
        extBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extBtnMouseClicked(evt);
            }
        });

        txBtn.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txBtn.setText("x");
        txBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout extBtnLayout = new javax.swing.GroupLayout(extBtn);
        extBtn.setLayout(extBtnLayout);
        extBtnLayout.setHorizontalGroup(
            extBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );
        extBtnLayout.setVerticalGroup(
            extBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extBtnLayout.createSequentialGroup()
                .addComponent(txBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel5.setBackground(new java.awt.Color(247, 148, 29));
        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 148, 29));
        jLabel5.setText("KOKO'S");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 37, 37));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CONTROL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(extBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 339, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 230, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxActionPerformed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void userTxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxMousePressed
        if (userTx.getText().equals("Ingrese su usuario")){
        userTx.setText("");
        userTx.setForeground(Color.black);
        }
        if (String.valueOf(passTx.getPassword()).isEmpty()){
        passTx.setText("********");
        passTx.setForeground(Color.gray);
        }
    }//GEN-LAST:event_userTxMousePressed

    private void passTxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxMousePressed
        // TODO add your handling code here:
        if (String.valueOf(passTx.getPassword()).equals("********")){
        passTx.setText("");
        passTx.setForeground(Color.black);
        }
        if (userTx.getText().isEmpty()){
        userTx.setText("Ingrese su usuario");
        userTx.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_passTxMousePressed

    private void passTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxActionPerformed

    private void extBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_extBtnMouseClicked

    private void txBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txBtnMouseEntered
        // TODO add your handling code here:
        extBtn.setBackground(Color.red);
        txBtn.setForeground(Color.white);
        
    }//GEN-LAST:event_txBtnMouseEntered

    private void txBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txBtnMouseExited
        // TODO add your handling code here:
        extBtn.setBackground(Color.white);
        txBtn.setForeground(Color.black);
    }//GEN-LAST:event_txBtnMouseExited

    private void txBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txBtnMouseClicked

    private void txEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txEntrarMouseClicked
        
       admincheck = DatosUser1[1];
       String contraseñaAdcheck = DatosUser1[4];
       String empleadocheck = DatosUser2[1];
       String contraseñaEmcheck = DatosUser2[4];
       usuario = userTx.getText();
       String contrasena = String.valueOf(passTx.getPassword()); 
       try{
        if (usuario.equals(admincheck) && contrasena.equals(contraseñaAdcheck)) {
           
            menu mn = new menu();
            mn.setVisible(true);
            this.dispose();
        } 
        else if (usuario.equals(empleadocheck ) && contrasena.equals(contraseñaEmcheck)) {
           
            menu mn = new menu();
            mn.setVisible(true);
            this.dispose();
        } 
        else 
        {
            if (usuario.isEmpty() || contrasena.isEmpty()) 
            {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            } 
            else 
            {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
                
            }
        } 
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(this, "error" + e, "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
            
       }
    }//GEN-LAST:event_txEntrarMouseClicked

    private void userTxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTxKeyTyped
        
    }//GEN-LAST:event_userTxKeyTyped

    private void txEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txEntrarMouseEntered
        // TODO add your handling code here:
        jPanel2.setBackground(Color.orange);
    }//GEN-LAST:event_txEntrarMouseEntered

    private void txEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txEntrarMouseExited
        // TODO add your handling code here:
        jPanel2.setBackground(new Color(247,148,29));
    }//GEN-LAST:event_txEntrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel extBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField passTx;
    private javax.swing.JLabel txBtn;
    public static javax.swing.JLabel txEntrar;
    private javax.swing.JLabel txLogin;
    private javax.swing.JTextField userTx;
    // End of variables declaration//GEN-END:variables
}
